<?php 
/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
 */

namespace UberAPILib\Models;

use JsonSerializable;

/**
 * The object that contains driver details.
 */
class Driver implements JsonSerializable {
    /**
     * The first name of the driver.
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * The formatted phone number for contacting the driver.
     * @required
     * @maps phone_number
     * @var string $phoneNumber public property
     */
    public $phoneNumber;

    /**
     * The URL to the photo of the driver.
     * @required
     * @maps picture_url
     * @var string $pictureUrl public property
     */
    public $pictureUrl;

    /**
     * The driver's star rating out of 5 stars.
     * @required
     * @var double $rating public property
     */
    public $rating;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $name           Initialization value for the property $this->name        
     * @param   string            $phoneNumber    Initialization value for the property $this->phoneNumber 
     * @param   string            $pictureUrl     Initialization value for the property $this->pictureUrl  
     * @param   double            $rating         Initialization value for the property $this->rating      
     */
    public function __construct()
    {
        if(4 == func_num_args())
        {
            $this->name         = func_get_arg(0);
            $this->phoneNumber  = func_get_arg(1);
            $this->pictureUrl   = func_get_arg(2);
            $this->rating       = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['name']         = $this->name;
        $json['phone_number'] = $this->phoneNumber;
        $json['picture_url']  = $this->pictureUrl;
        $json['rating']       = $this->rating;

        return $json;
    }
}