<?php 
/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
 */

namespace UberAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Errors implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @required
     * @var string $code public property
     */
    public $code;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $status public property
     */
    public $status;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $title public property
     */
    public $title;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $code     Initialization value for the property $this->code  
     * @param   integer           $status   Initialization value for the property $this->status
     * @param   string            $title    Initialization value for the property $this->title 
     */
    public function __construct()
    {
        if(3 == func_num_args())
        {
            $this->code   = func_get_arg(0);
            $this->status = func_get_arg(1);
            $this->title  = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['code']   = $this->code;
        $json['status'] = $this->status;
        $json['title']  = $this->title;

        return $json;
    }
}