<?php 
/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
 */

namespace UberAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ErrorBase implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @required
     * @var Errors[] $errors public property
     */
    public $errors;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $meta public property
     */
    public $meta;

    /**
     * Constructor to set initial or default values of member properties
     * @param   array             $errors   Initialization value for the property $this->errors
     * @param   string            $meta     Initialization value for the property $this->meta  
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->errors = func_get_arg(0);
            $this->meta   = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['errors'] = $this->errors;
        $json['meta']   = $this->meta;

        return $json;
    }
}