<?php 
/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
 */

namespace UberAPILib\Models;

use JsonSerializable;

/**
 * A history of pickup and dropoff
 */
class History implements JsonSerializable {
    /**
     * Distance travelled
     * @required
     * @var double $distance public property
     */
    public $distance;

    /**
     * Location where journey ended
     * @required
     * @maps end_location
     * @var Location $endLocation public property
     */
    public $endLocation;

    /**
     * Time of journey end
     * @required
     * @maps end_time
     * @var integer $endTime public property
     */
    public $endTime;

    /**
     * The product that was used
     * @required
     * @maps product_id
     * @var string $productId public property
     */
    public $productId;

    /**
     * Time when requested
     * @required
     * @maps request_time
     * @var integer $requestTime public property
     */
    public $requestTime;

    /**
     * Location of starting the journey
     * @required
     * @maps start_location
     * @var Location $startLocation public property
     */
    public $startLocation;

    /**
     * Time of starting the journey
     * @required
     * @maps start_time
     * @var integer $startTime public property
     */
    public $startTime;

    /**
     * Status of the product e.g., completed
     * @required
     * @var string $status public property
     */
    public $status;

    /**
     * History item id
     * @required
     * @var string $uuid public property
     */
    public $uuid;

    /**
     * Constructor to set initial or default values of member properties
     * @param   double            $distance         Initialization value for the property $this->distance      
     * @param   Location          $endLocation      Initialization value for the property $this->endLocation   
     * @param   integer           $endTime          Initialization value for the property $this->endTime       
     * @param   string            $productId        Initialization value for the property $this->productId     
     * @param   integer           $requestTime      Initialization value for the property $this->requestTime   
     * @param   Location          $startLocation    Initialization value for the property $this->startLocation 
     * @param   integer           $startTime        Initialization value for the property $this->startTime     
     * @param   string            $status           Initialization value for the property $this->status        
     * @param   string            $uuid             Initialization value for the property $this->uuid          
     */
    public function __construct()
    {
        if(9 == func_num_args())
        {
            $this->distance       = func_get_arg(0);
            $this->endLocation    = func_get_arg(1);
            $this->endTime        = func_get_arg(2);
            $this->productId      = func_get_arg(3);
            $this->requestTime    = func_get_arg(4);
            $this->startLocation  = func_get_arg(5);
            $this->startTime      = func_get_arg(6);
            $this->status         = func_get_arg(7);
            $this->uuid           = func_get_arg(8);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['distance']       = $this->distance;
        $json['end_location']   = $this->endLocation;
        $json['end_time']       = $this->endTime;
        $json['product_id']     = $this->productId;
        $json['request_time']   = $this->requestTime;
        $json['start_location'] = $this->startLocation;
        $json['start_time']     = $this->startTime;
        $json['status']         = $this->status;
        $json['uuid']           = $this->uuid;

        return $json;
    }
}