<?php 
/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
 */

namespace UberAPILib\Models;

use JsonSerializable;

/**
 * Location with address
 */
class Location implements JsonSerializable {
    /**
     * The address in user readable form
     * @required
     * @var string $address public property
     */
    public $address;

    /**
     * Latitude component of location.
     * @required
     * @var double $latitude public property
     */
    public $latitude;

    /**
     * Longitude component of location.
     * @required
     * @var double $longitude public property
     */
    public $longitude;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $address     Initialization value for the property $this->address  
     * @param   double            $latitude    Initialization value for the property $this->latitude 
     * @param   double            $longitude   Initialization value for the property $this->longitude
     */
    public function __construct()
    {
        if(3 == func_num_args())
        {
            $this->address   = func_get_arg(0);
            $this->latitude  = func_get_arg(1);
            $this->longitude = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['address']   = $this->address;
        $json['latitude']  = $this->latitude;
        $json['longitude'] = $this->longitude;

        return $json;
    }
}