<?php 
/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
 */

namespace UberAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Meta implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @required
     * @maps surge_confirmation
     * @var SurgeConfirmation $surgeConfirmation public property
     */
    public $surgeConfirmation;

    /**
     * Constructor to set initial or default values of member properties
     * @param   SurgeConfirmation   $surgeConfirmation    Initialization value for the property $this->surgeConfirmation 
     */
    public function __construct()
    {
        if(1 == func_num_args())
        {
            $this->surgeConfirmation  = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['surge_confirmation'] = $this->surgeConfirmation;

        return $json;
    }
}