<?php 
/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
 */

namespace UberAPILib\Models;

use JsonSerializable;

/**
 * Collection of price estimates
 */
class PriceEstimateCollection implements JsonSerializable {
    /**
     * List of price estimates
     * @required
     * @var PriceEsitmate[] $prices public property
     */
    public $prices;

    /**
     * Constructor to set initial or default values of member properties
     * @param   array             $prices   Initialization value for the property $this->prices
     */
    public function __construct()
    {
        if(1 == func_num_args())
        {
            $this->prices = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['prices'] = $this->prices;

        return $json;
    }
}