<?php 
/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
 */

namespace UberAPILib\Models;

use JsonSerializable;

/**
 * Information about promotions
 */
class PromotionsResponse implements JsonSerializable {
    /**
     * A localized string we recommend to use when offering the promotion to users.
     * @required
     * @maps display_text
     * @var string $displayText public property
     */
    public $displayText;

    /**
     * The value of the promotion that is available to a user in this location in the local currency.
     * @required
     * @maps localized_value
     * @var string $localizedValue public property
     */
    public $localizedValue;

    /**
     * The type of the promo which is either "trip_credit" or "account_credit".
     * @required
     * @var string $type public property
     */
    public $type;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $displayText       Initialization value for the property $this->displayText    
     * @param   string            $localizedValue    Initialization value for the property $this->localizedValue 
     * @param   string            $type              Initialization value for the property $this->type           
     */
    public function __construct()
    {
        if(3 == func_num_args())
        {
            $this->displayText     = func_get_arg(0);
            $this->localizedValue  = func_get_arg(1);
            $this->type            = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['display_text']    = $this->displayText;
        $json['localized_value'] = $this->localizedValue;
        $json['type']            = $this->type;

        return $json;
    }
}