<?php 
/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
 */

namespace UberAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class SurgeConfirmation implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @required
     * @var string $href public property
     */
    public $href;

    /**
     * @todo Write general description for this property
     * @required
     * @maps surge_confirmation_id
     * @var string $surgeConfirmationId public property
     */
    public $surgeConfirmationId;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $href                    Initialization value for the property $this->href                 
     * @param   string            $surgeConfirmationId     Initialization value for the property $this->surgeConfirmationId  
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->href                  = func_get_arg(0);
            $this->surgeConfirmationId   = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['href']                  = $this->href;
        $json['surge_confirmation_id'] = $this->surgeConfirmationId;

        return $json;
    }
}