<?php 
/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
 */

namespace UberAPILib\Models;

use JsonSerializable;

/**
 * Time estimates e.g., ETA
 */
class TimeEstimate implements JsonSerializable {
    /**
     * Display name of product.
     * @required
     * @maps display_name
     * @var string $displayName public property
     */
    public $displayName;

    /**
     * ETA for the product (in seconds). Always show estimate in minutes.
     * @required
     * @var integer $estimate public property
     */
    public $estimate;

    /**
     * Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
     * @required
     * @maps product_id
     * @var string $productId public property
     */
    public $productId;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $displayName    Initialization value for the property $this->displayName 
     * @param   integer           $estimate       Initialization value for the property $this->estimate    
     * @param   string            $productId      Initialization value for the property $this->productId   
     */
    public function __construct()
    {
        if(3 == func_num_args())
        {
            $this->displayName  = func_get_arg(0);
            $this->estimate     = func_get_arg(1);
            $this->productId    = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['display_name'] = $this->displayName;
        $json['estimate']     = $this->estimate;
        $json['product_id']   = $this->productId;

        return $json;
    }
}