<?php 
/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
 */

namespace UberAPILib\Models;

use JsonSerializable;

/**
 * Collection of time estimates
 */
class TimeEstimateCollection implements JsonSerializable {
    /**
     * List of time estimates
     * @required
     * @var TimeEstimate[] $times public property
     */
    public $times;

    /**
     * Constructor to set initial or default values of member properties
     * @param   array             $times   Initialization value for the property $this->times
     */
    public function __construct()
    {
        if(1 == func_num_args())
        {
            $this->times = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['times'] = $this->times;

        return $json;
    }
}