<?php 
/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
 */

namespace UberAPILib\Models;

use JsonSerializable;

/**
 * User profile information
 */
class UserProfile implements JsonSerializable {
    /**
     * Email address of the Uber user
     * @required
     * @var string $email public property
     */
    public $email;

    /**
     * First name of the Uber user.
     * @required
     * @maps first_name
     * @var string $firstName public property
     */
    public $firstName;

    /**
     * Last name of the Uber user.
     * @required
     * @maps last_name
     * @var string $lastName public property
     */
    public $lastName;

    /**
     * Image URL of the Uber user.
     * @required
     * @var string $picture public property
     */
    public $picture;

    /**
     * Promo code of the Uber user.
     * @required
     * @maps promo_code
     * @var string $promoCode public property
     */
    public $promoCode;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $email        Initialization value for the property $this->email     
     * @param   string            $firstName    Initialization value for the property $this->firstName 
     * @param   string            $lastName     Initialization value for the property $this->lastName  
     * @param   string            $picture      Initialization value for the property $this->picture   
     * @param   string            $promoCode    Initialization value for the property $this->promoCode 
     */
    public function __construct()
    {
        if(5 == func_num_args())
        {
            $this->email      = func_get_arg(0);
            $this->firstName  = func_get_arg(1);
            $this->lastName   = func_get_arg(2);
            $this->picture    = func_get_arg(3);
            $this->promoCode  = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['email']      = $this->email;
        $json['first_name'] = $this->firstName;
        $json['last_name']  = $this->lastName;
        $json['picture']    = $this->picture;
        $json['promo_code'] = $this->promoCode;

        return $json;
    }
}